$axure.loadCurrentPage({
  "url":"高级设置.html",
  "generationDate":new Date(1426478511090.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"684ab7419533479bacabe47534ac6308",
    "type":"Axure:Page",
    "name":"高级设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0e1f23f698ce48329adc06d43bb74c81",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":100,
              "y":80},
            "size":{
              "width":320,
              "height":510}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"711eb70dc7214fedb4a6c9e72caeafc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":100,
                  "y":80},
                "size":{
                  "width":320,
                  "height":510}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/palm_call/u2.png"}},
{
          "id":"a92b3dde4553476c9020e2cdf2560097",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":454,
              "y":80},
            "size":{
              "width":286,
              "height":510}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bafccffd891e49d2b5dd1a941c8a6670",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":454,
                  "y":80},
                "size":{
                  "width":286,
                  "height":510}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/高级设置/u2.png"}},
{
          "id":"a117177a375e46c9b7e0a64c2dda7bca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":100,
              "y":80},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12215c7d0b724ef19c4d9ab22a3dd92f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":100,
                  "y":80},
                "size":{
                  "width":320,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/palm_call/u4.png"}},
{
          "id":"b32ee143ad154976a9797930dcafd5d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":108,
              "y":88},
            "size":{
              "width":15,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01b82d9b8d2e400e9806487c3ab025f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":108,
                  "y":88},
                "size":{
                  "width":15,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ad9d76d6c0143afbe2c16d22723520d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":108,
              "y":135},
            "size":{
              "width":304,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"969ca772d6124a2986598e39b82fc7f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":108,
                  "y":135},
                "size":{
                  "width":304,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u4.png"}},
{
          "id":"32a2048d91dc4745b37829fff954f22d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":108,
              "y":180},
            "size":{
              "width":304,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e38bcd2700294da0b15a4ce220bb9c10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":108,
                  "y":180},
                "size":{
                  "width":304,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u4.png"}},
{
          "id":"095dfa29d174498eb5b931bbb2941dc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":108,
              "y":225},
            "size":{
              "width":304,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7283a80fa366408c8d6430e7d99ffe8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":108,
                  "y":225},
                "size":{
                  "width":304,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u4.png"}},
{
          "id":"a36fc18a75654ad3a05ea0c5f3b06767",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":108,
              "y":270},
            "size":{
              "width":304,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26e1b929ed5547708a6ebd31d45c54f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":108,
                  "y":270},
                "size":{
                  "width":304,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u4.png"}},
{
          "id":"bd90e3199d9743118b4c1d2a5a08efc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":108,
              "y":315},
            "size":{
              "width":304,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bab28bd20bce4c55a5037cadce52b500",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":108,
                  "y":315},
                "size":{
                  "width":304,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u4.png"}},
{
          "id":"acc7fb124418449095336f38154bc500",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":108,
              "y":360},
            "size":{
              "width":304,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4048691b67fc4025a84aa368e4ddb18e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":108,
                  "y":360},
                "size":{
                  "width":304,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0e1f23f698ce48329adc06d43bb74c81":{
      "scriptId":"u0"},
    "711eb70dc7214fedb4a6c9e72caeafc4":{
      "scriptId":"u1"},
    "a92b3dde4553476c9020e2cdf2560097":{
      "scriptId":"u2"},
    "bafccffd891e49d2b5dd1a941c8a6670":{
      "scriptId":"u3"},
    "a117177a375e46c9b7e0a64c2dda7bca":{
      "scriptId":"u4"},
    "12215c7d0b724ef19c4d9ab22a3dd92f":{
      "scriptId":"u5"},
    "b32ee143ad154976a9797930dcafd5d4":{
      "scriptId":"u6"},
    "01b82d9b8d2e400e9806487c3ab025f5":{
      "scriptId":"u7"},
    "0ad9d76d6c0143afbe2c16d22723520d":{
      "scriptId":"u8"},
    "969ca772d6124a2986598e39b82fc7f3":{
      "scriptId":"u9"},
    "32a2048d91dc4745b37829fff954f22d":{
      "scriptId":"u10"},
    "e38bcd2700294da0b15a4ce220bb9c10":{
      "scriptId":"u11"},
    "095dfa29d174498eb5b931bbb2941dc8":{
      "scriptId":"u12"},
    "7283a80fa366408c8d6430e7d99ffe8e":{
      "scriptId":"u13"},
    "a36fc18a75654ad3a05ea0c5f3b06767":{
      "scriptId":"u14"},
    "26e1b929ed5547708a6ebd31d45c54f5":{
      "scriptId":"u15"},
    "bd90e3199d9743118b4c1d2a5a08efc7":{
      "scriptId":"u16"},
    "bab28bd20bce4c55a5037cadce52b500":{
      "scriptId":"u17"},
    "acc7fb124418449095336f38154bc500":{
      "scriptId":"u18"},
    "4048691b67fc4025a84aa368e4ddb18e":{
      "scriptId":"u19"}}});